name: Build UpinnSecretsiOSLib

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Instalar Rust (para UniFFI)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Verificar Swift
      run: swift --version

    - name: Build Swift Package
      run: swift build

    - name: Run Swift Tests
      run: swift test
